http://ithelp.ithome.com.tw/articles/10185819

# numpy 與 ndarray 的常用屬性或方法

瞭解 ndarray 的概觀

>+ ndim 屬性
>+ shape 屬性
>+ dtype 屬性

In [1]:
import numpy as np

# 截至 2016-12-06 上午 7 時第 8 屆 iT 邦幫忙各組的鐵人分別是 56、8、19、14、6 與 71 人
ironmen = [56, 8, 19, 14, 6, 71]
ironmen_array = np.array(ironmen)

print(ironmen_array.ndim) # number of dimensions
print(ironmen_array.shape) # m*n
print(ironmen_array.dtype) # 資料類型
print("\n") # 空一行

# 2d array
ironmen_2d = [range(1, 7), [56, 8, 19, 14, 6, 71]]
ironmen_2d_array = np.array(ironmen_2d)
print(ironmen_2d_array.ndim) # number of dimensions
print(ironmen_2d_array.shape) # m*n
print(ironmen_2d_array.dtype) # 資料類型

1
(6,)
int32


2
(2, 6)
int32


# 建立 ndarray

numpy 套件除了 array() 方法可以將 list 轉換成 ndarray，還有其他的方法可以建立 ndarray。

>+ zeros() 方法
>+ empty() 方法
>+ arange() 方法

In [2]:
import numpy as np

print(np.zeros(6)) # 六個元素均為零的 1d array
print("------") # 分隔線
print(np.zeros((2, 6))) # 十二個元素均為零的 2d array
print("------") # 分隔線
print(np.empty((2, 6, 2))) # 二十四個元素均為未初始化的值
print("------") # 分隔線
print(np.arange(11)) # 十一個元素為 0 到 10 的 1d array

[ 0.  0.  0.  0.  0.  0.]
------
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
------
[[[  6.23042070e-307   3.56043053e-307]
  [  1.60219306e-306   2.44763557e-307]
  [  1.69119330e-306   7.56599807e-307]
  [  8.90104239e-307   1.24610383e-306]
  [  1.69118108e-306   8.06632139e-308]
  [  1.20160711e-306   1.69119330e-306]]

 [[  1.29062229e-306   1.60217812e-306]
  [  1.37961370e-306   1.78020712e-306]
  [  8.90104239e-307   1.05700515e-307]
  [  1.11261774e-306   1.29060871e-306]
  [  8.34424766e-308   8.34445138e-308]
  [  7.56577398e-307   9.34600284e-307]]]
------
[ 0  1  2  3  4  5  6  7  8  9 10]


# 轉換變數類型

ndarray 的 astype() 方法可以轉換變數類型。

In [3]:
import numpy as np

ironmen = ["56", "8", "19", "14", "6", "71"]
ironmen_str_array = np.array(ironmen)
print(ironmen_str_array.dtype)
print("---") # 分隔線

# 轉換為 int64
ironmen_int_array = ironmen_str_array.astype(np.int64)
print(ironmen_int_array.dtype)

<U2
---
int64


# 用索引值進行篩選

利用 [ ] 搭配索引值篩選 ndarray，這點與 R 語言作法相同。

In [4]:
import numpy as np

my_array = np.arange(10)
print(my_array[0])
print(my_array[0:5])
print("---") # 分隔線

my_2d_array = np.array([np.arange(0, 5), np.arange(5, 10)])
print(my_2d_array)
print("---") # 分隔線
print(my_2d_array[1, :]) # 第二列
print(my_2d_array[:, 1]) # 第二欄
print(my_2d_array[1, 1]) # 第二列第二欄的元素

0
[0 1 2 3 4]
---
[[0 1 2 3 4]
 [5 6 7 8 9]]
---
[5 6 7 8 9]
[1 6]
6


# 用布林值進行篩選

利用布林值（bool）篩選 ndarray，，這點與 R 語言作法相同。

In [5]:
import numpy as np

ironmen = [56, 8, 19, 14, 6, 71]
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen_array = np.array(ironmen)
groups_array = np.array(groups)

# 用人數去篩選組別
print(ironmen_array >= 10) # 布林值陣列
print(groups_array[ironmen_array >= 10]) # 鐵人數大於 10 的組別

# 用組別去篩選人數
print(groups_array != "自我挑戰組") # 布林值陣列
print(ironmen_array[groups_array != "自我挑戰組"]) # 除了自我挑戰組以外的鐵人數

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# 2d array 轉置

使用 T 屬性。

In [6]:
import numpy as np

# 建立一個 2d array
my_1d_array = np.arange(10)
my_2d_array = my_1d_array.reshape((2, 5))
print(my_2d_array)
print("---") # 分隔線
print(my_2d_array.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
---
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


# numpy 的 where 方法

透過 numpy 的 where() 方法在 ndarray 中進行流程控制。

In [7]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, np.nan])
np.where(np.isnan(ironmen_array), 71, ironmen_array)

array([ 56.,   8.,  19.,  14.,   6.,  71.])

# 排序

透過 sort() 方法。

In [8]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, 71])
print(ironmen_array)
ironmen_array.sort()
print(ironmen_array)

[56  8 19 14  6 71]
[ 6  8 14 19 56 71]


# 隨機變數

透過 numpy 的 random() 方法可以生成隨機變數。

In [9]:
import numpy as np

normal_samples = np.random.normal(size = 10) # 生成 10 組標準常態分配（平均值為 0，標準差為 1 的常態分配）隨機變數
uniform_samples = np.random.uniform(size = 10) # 生成 10 組介於 0 與 1 之間均勻分配隨機變數

print(normal_samples)
print("---") # 分隔線
print(uniform_samples)


[-2.08399972  1.05344414  0.87786332  0.57413661 -0.19495045 -0.98848911
  0.52060073 -0.05162372  1.27765032  0.1311543 ]
---
[ 0.3703264   0.86928318  0.74901159  0.48212249  0.92449832  0.91211106
  0.12967045  0.6816452   0.27952486  0.60570259]
