http://ithelp.ithome.com.tw/articles/10185093

R 語言我們直接用一個 vector 儲存各組人數後乘以 30，就能得到一個 element-wise 的計算結果，這就是我們要的答案。

In [1]:
ironmen <- c(46, 8, 11, 11, 4, 56)
articles <- ironmen * 30
articles

[1] 1380  240  330  330  120 1680

# R 語言的 vector 與 matrix

單一資料類型

R 語言的 vector 與 matrix 都只能容許一種資料類型，

如果同時儲存有數值，邏輯值，會被自動轉換為數值，

如果同時儲存有數值，邏輯值與文字，會被自動轉換為文字。

In [5]:
my_vector <- c(1, TRUE)
class(my_vector) # "numeric"

my_vector <- c(1, TRUE, "one")
class(my_vector) # "character"

my_matrix <- matrix(c(1, 0, TRUE, FALSE), nrow = 2)
my_matrix

my_matrix <- matrix(c(1, "zero", TRUE, FALSE), nrow = 2)
my_matrix

[1] "numeric"

[1] "character"

[,1] [,2]
[1,] 1    1   
[2,] 0    0

[,1] [,2] 
[1,] 1    TRUE 
[2,] zero FALSE

# Element-wise 運算

In [6]:
my_vector <- 1:4
my_vector ^ 2

my_matrix <- matrix(my_vector, nrow = 2)
my_matrix ^ 2

[1]  1  4  9 16

[,1] [,2]
[1,] 1     9  
[2,] 4    16

# 選擇元素

R 語言的 vector 與 matrix 都透過中括號 [] 或者邏輯值選擇元素。

In [7]:
# vector
ironmen <- c(46, 8, 11, 11, 4, 56)
ironmen[1] # 選出 Modern Web 組的鐵人數

ironmen > 10 # 哪幾組的鐵人數超過 10 人

ironmen[ironmen > 10] # 超過 10 人的鐵人數

names(ironmen) <- c("Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組") # 把 vector 的元素加上名稱
names(ironmen[ironmen > 10]) # 超過 10 人參賽的組別名

[1] 46

[1]  TRUE FALSE  TRUE  TRUE FALSE  TRUE

[1] 46 11 11 56

[1] "Modern Web" "Cloud"      "Big Data"   "自我挑戰組"

In [8]:
# matrix
ironmen <- c(46, 8, 11, 11, 4, 56)
ironmen_mat <- matrix(ironmen, nrow = 2)
ironmen_mat[1, 1] # 選出 Modern Web 組的鐵人數

ironmen_mat > 10 # 哪幾組的鐵人數超過 10 人

ironmen_mat[ironmen_mat > 10] # 超過 10 人的鐵人數

[1] 46

[,1]  [,2] [,3] 
[1,]  TRUE TRUE FALSE
[2,] FALSE TRUE  TRUE

[1] 46 11 11 56

# 了解 matrix 規模的函數

R 語言可以透過 length() 與 dim() 函數來了解 matrix 的規模。

In [9]:
ironmen <- c(46, 8, 11, 11, 4, 56)
ironmen_mat <- matrix(ironmen, nrow = 2)
length(ironmen_mat)

dim(ironmen_mat)

[1] 6

[1] 2 3