http://ithelp.ithome.com.tw/articles/10185093

# ndarray

In [3]:
import numpy as np # 引用套件並縮寫為 np

ironmen = np.array([46, 8, 11, 11, 4, 56]) # 將 list 透過 numpy 的 array 方法進行轉換
print(ironmen) # 看看 ironmen 的外觀
print(type(ironmen)) # 看看 ironmen 的資料結構
articles = ironmen * 30
print(articles)

[46  8 11 11  4 56]
<class 'numpy.ndarray'>
[1380  240  330  330  120 1680]


# NumPy 的 ndarray

單一資料類型

NumPy 的 ndarray 只能容許一種資料類型，

如果同時儲存有數值，布林值，會被自動轉換為數值，

如果同時儲存有數值，布林值與文字，會被自動轉換為文字。

In [4]:
import numpy as np

# 一維
my_np_array = np.array([1, True])
print(my_np_array.dtype) # int64

my_np_array = np.array([1, True, "one"])
print(my_np_array.dtype) # unicode_21


int32
<U11


In [5]:
import numpy as np

# 二維
my_2d_array = np.array([[1, True],
                        [0, False]])
print(my_2d_array)

my_2d_array = np.array([[1, True],
                        ["zero", False]])
print(my_2d_array)

[[1 1]
 [0 0]]
[['1' 'True']
 ['zero' 'False']]


# Element-wise 運算

NumPy 的 ndarray 完全支持 element-wise 運算。

In [6]:
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array ** 2)

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array ** 2)

[ 1  4  9 16]
[[ 1  9]
 [ 4 16]]


# 選擇元素

NumPy 的 ndarray 透過中括號 [] 或者布林值選擇元素。

In [7]:
import numpy as np

ironmen = np.array([46, 8, 11, 11, 4, 56])

print(ironmen[0]) # 選出 Modern Web 組的鐵人數
print(ironmen > 10) # 哪幾組的鐵人數超過 10 人
print(ironmen[ironmen > 10]) # 超過 10 人的鐵人數

46
[ True False  True  True False  True]
[46 11 11 56]


In [8]:
import numpy as np

ironmen_2d_array = np.array([[46, 11, 4],
                            [8, 11, 56]])

print(ironmen_2d_array[0, 0]) # 選出 Modern Web 組的鐵人數
print(ironmen_2d_array > 10) # 哪幾組的鐵人數超過 10 人
print(ironmen_2d_array[ironmen_2d_array > 10]) # 超過 10 人的鐵人數

46
[[ True  True False]
 [False  True  True]]
[46 11 11 56]


# 了解 2d array 外觀的屬性

NumPy 可以透過 .size 與 .shape 來了解 2d array 的規模。

In [9]:
import numpy as np

ironmen_2d_array = np.array([[46, 11, 4],
                            [8, 11, 56]])
print(ironmen_2d_array.size) # 6
print(ironmen_2d_array.shape) # (2, 3)

6
(2, 3)
